"""Create tables and seed sample jobs (idempotent). Run: python -m app.seed"""

import logging
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import select

from .database import SessionLocal, init_db
from .models import Company, Job

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def seed_jobs() -> int:
    today = date.today()
    seed_data = [
        {
            "source_id": "internal:ai-engineer",
            "source": "JobPilot",
            "title": "AI Engineer",
            "company_name": "Fractal Analytics",
            "industry": "Analytics",
            "rating": 4.2,
            "location": "Bengaluru, India",
            "work_mode": "Hybrid",
            "employment_type": "Full-time",
            "salary_min": 1800000,
            "salary_max": 3200000,
            "experience_required": "1-3 years",
            "deadline_offset": 20,
            "skills_required": [
                "Python",
                "Machine Learning",
                "Deep Learning",
                "NLP",
                "TensorFlow",
                "SQL",
                "Docker",
            ],
            "description": "Design and ship production ML systems for enterprise clients. Work on NLP and computer vision models, build training pipelines, and deploy with Docker/Kubernetes. Collaborate with data engineers and product teams end to end.",
            "benefits": ["Health insurance", "Learning budget", "Hybrid work"],
        },
        {
            "source_id": "internal:data-scientist",
            "source": "JobPilot",
            "title": "Data Scientist",
            "company_name": "Mu Sigma",
            "industry": "Data & AI",
            "rating": 3.9,
            "location": "Bengaluru, India",
            "work_mode": "Onsite",
            "employment_type": "Full-time",
            "salary_min": 1200000,
            "salary_max": 2200000,
            "experience_required": "0-2 years",
            "deadline_offset": 15,
            "skills_required": [
                "Python",
                "Machine Learning",
                "SQL",
                "Statistics",
                "Pandas",
                "NumPy",
                "Power BI",
            ],
            "description": "Build decision science solutions for Fortune 500 clients. Perform exploratory analysis, build statistical models, create dashboards, and communicate insights to stakeholders.",
            "benefits": ["Training programs", "Health cover"],
        },
        {
            "source_id": "internal:backend-dev",
            "source": "JobPilot",
            "title": "Backend Developer (FastAPI)",
            "company_name": "Razorpay",
            "industry": "Fintech",
            "rating": 4.4,
            "location": "Bengaluru, India",
            "work_mode": "Hybrid",
            "employment_type": "Full-time",
            "salary_min": 1500000,
            "salary_max": 3000000,
            "experience_required": "1-3 years",
            "deadline_offset": 12,
            "skills_required": [
                "Python",
                "FastAPI",
                "SQL",
                "PostgreSQL",
                "Redis",
                "Docker",
                "REST APIs",
                "System Design",
            ],
            "description": "Build high-throughput payment APIs. Design microservices, optimize Postgres queries, add caching with Redis, and ship reliable REST endpoints serving millions of transactions.",
            "benefits": ["ESOPs", "Medical insurance", "Meals"],
        },
        {
            "source_id": "internal:ml-intern",
            "source": "JobPilot",
            "title": "Machine Learning Intern",
            "company_name": "Google",
            "industry": "Technology",
            "rating": 4.5,
            "location": "Bengaluru, India",
            "work_mode": "Hybrid",
            "employment_type": "Internship",
            "salary_min": 60000,
            "salary_max": 90000,
            "experience_required": "Fresher",
            "deadline_offset": 10,
            "skills_required": [
                "Python",
                "Machine Learning",
                "TensorFlow",
                "PyTorch",
                "NLP",
                "SQL",
            ],
            "description": "Work with research engineers on applied ML. Contribute to model training, evaluation pipelines, and exploratory research. Strong CS fundamentals and hands-on ML projects required.",
            "benefits": ["Stipend", "Mentorship", "Free food"],
        },
        {
            "source_id": "internal:sw-intern",
            "source": "JobPilot",
            "title": "Software Engineering Intern",
            "company_name": "Zomato",
            "industry": "Consumer Tech",
            "rating": 4.1,
            "location": "Gurugram, India",
            "work_mode": "Onsite",
            "employment_type": "Internship",
            "salary_min": 40000,
            "salary_max": 60000,
            "experience_required": "Fresher",
            "deadline_offset": 25,
            "skills_required": [
                "Python",
                "JavaScript",
                "React",
                "SQL",
                "Docker",
                "REST APIs",
                "Git",
            ],
            "description": "Join a product engineering squad building consumer-facing features. Ship frontend and backend code, write tests, and collaborate with PMs and designers in an agile team.",
            "benefits": ["Stipend", "PPO opportunity", "Meals"],
        },
        {
            "source_id": "internal:data-eng-intern",
            "source": "JobPilot",
            "title": "Data Engineering Intern",
            "company_name": "Flipkart",
            "industry": "E-commerce",
            "rating": 4.0,
            "location": "Bengaluru, India",
            "work_mode": "Hybrid",
            "employment_type": "Internship",
            "salary_min": 45000,
            "salary_max": 65000,
            "experience_required": "Fresher",
            "deadline_offset": 18,
            "skills_required": [
                "Python",
                "SQL",
                "Spark",
                "Hadoop",
                "Airflow",
                "Data Warehousing",
            ],
            "description": "Help build scalable data pipelines for e-commerce analytics. Work on data ingestion, transformation with Spark, and maintain warehouse schemas.",
            "benefits": ["Stipend", "PPO opportunity"],
        },
        {
            "source_id": "internal:frontend-intern",
            "source": "JobPilot",
            "title": "Frontend Developer Intern",
            "company_name": "CRED",
            "industry": "Fintech",
            "rating": 4.3,
            "location": "Bengaluru, India",
            "work_mode": "Onsite",
            "employment_type": "Internship",
            "salary_min": 50000,
            "salary_max": 80000,
            "experience_required": "Fresher",
            "deadline_offset": 30,
            "skills_required": [
                "JavaScript",
                "TypeScript",
                "React",
                "Tailwind CSS",
                "REST APIs",
            ],
            "description": "Build beautiful, performant interfaces for a premium fintech product. Work with React and TypeScript, focus on design systems and smooth animations.",
            "benefits": ["Stipend", "Mentorship"],
        },
        {
            "source_id": "internal:llm-engineer",
            "source": "JobPilot",
            "title": "LLM Engineer",
            "company_name": "Krutrim AI",
            "industry": "AI Startup",
            "rating": 4.2,
            "location": "Bengaluru, India",
            "work_mode": "Remote",
            "employment_type": "Full-time",
            "salary_min": 2000000,
            "salary_max": 4000000,
            "experience_required": "1-4 years",
            "deadline_offset": 14,
            "skills_required": [
                "Python",
                "LLM",
                "RAG",
                "PyTorch",
                "Transformers",
                "FastAPI",
                "Vector Databases",
                "NLP",
            ],
            "description": "Build LLM-powered products. Implement RAG pipelines, fine-tune open models, design evaluation harnesses, and ship production APIs with FastAPI.",
            "benefits": ["Remote work", "ESOPs", "Compute budget"],
        },
        {
            "source_id": "internal:devops-intern",
            "source": "JobPilot",
            "title": "DevOps Intern",
            "company_name": "Jio Platforms",
            "industry": "Telecom Tech",
            "rating": 4.0,
            "location": "Mumbai, India",
            "work_mode": "Onsite",
            "employment_type": "Internship",
            "salary_min": 35000,
            "salary_max": 50000,
            "experience_required": "Fresher",
            "deadline_offset": 22,
            "skills_required": [
                "Linux",
                "Docker",
                "Kubernetes",
                "AWS",
                "CI/CD",
                "Terraform",
                "Bash",
            ],
            "description": "Assist in automating cloud infrastructure. Work with Docker/Kubernetes, set up CI/CD with GitHub Actions, and manage AWS resources.",
            "benefits": ["Stipend", "PPO opportunity"],
        },
        {
            "source_id": "internal:data-analyst",
            "source": "JobPilot",
            "title": "Data Analyst",
            "company_name": "Swiggy",
            "industry": "Consumer Tech",
            "rating": 4.1,
            "location": "Bengaluru, India",
            "work_mode": "Hybrid",
            "employment_type": "Full-time",
            "salary_min": 900000,
            "salary_max": 1600000,
            "experience_required": "0-2 years",
            "deadline_offset": 9,
            "skills_required": [
                "SQL",
                "Excel",
                "Python",
                "Power BI",
                "Statistics",
                "Data Visualization",
            ],
            "description": "Analyze user behavior and growth metrics. Build dashboards, run experiments, and partner with product teams on data-driven decisions.",
            "benefits": ["Health insurance", "Food credits"],
        },
        {
            "source_id": "internal:fullstack-dev",
            "source": "JobPilot",
            "title": "Full Stack Developer",
            "company_name": "Zerodha",
            "industry": "Fintech",
            "rating": 4.6,
            "location": "Bengaluru, India",
            "work_mode": "Onsite",
            "employment_type": "Full-time",
            "salary_min": 1200000,
            "salary_max": 2400000,
            "experience_required": "1-3 years",
            "deadline_offset": 16,
            "skills_required": [
                "Python",
                "Django",
                "React",
                "PostgreSQL",
                "Redis",
                "JavaScript",
                "REST APIs",
            ],
            "description": "Build trading and portfolio products used by millions. Own features across the stack from Postgres queries to React UI.",
            "benefits": ["ESOPs", "Health insurance"],
        },
        {
            "source_id": "internal:ai-intern",
            "source": "JobPilot",
            "title": "AI Research Intern",
            "company_name": "Sarvam AI",
            "industry": "AI Startup",
            "rating": 4.3,
            "location": "Remote",
            "work_mode": "Remote",
            "employment_type": "Internship",
            "salary_min": 50000,
            "salary_max": 90000,
            "experience_required": "Fresher",
            "deadline_offset": 11,
            "skills_required": [
                "Python",
                "Machine Learning",
                "NLP",
                "PyTorch",
                "Transformers",
                "Hugging Face",
            ],
            "description": "Research and prototype Indian-language AI models. Contribute to datasets, model training experiments, and evaluation. Papers welcome.",
            "benefits": ["Stipend", "Remote work", "Mentorship"],
        },
        {
            "source_id": "internal:mobile-intern",
            "source": "JobPilot",
            "title": "React Native Developer Intern",
            "company_name": "Urban Company",
            "industry": "Marketplace",
            "rating": 4.0,
            "location": "Gurugram, India",
            "work_mode": "Hybrid",
            "employment_type": "Internship",
            "salary_min": 30000,
            "salary_max": 50000,
            "experience_required": "Fresher",
            "deadline_offset": 19,
            "skills_required": [
                "JavaScript",
                "React Native",
                "TypeScript",
                "Redux",
                "REST APIs",
                "Git",
            ],
            "description": "Build features for a leading home-services marketplace app. Work with React Native, manage state with Redux, and ship weekly.",
            "benefits": ["Stipend", "PPO opportunity"],
        },
        {
            "source_id": "internal:product-analyst",
            "source": "JobPilot",
            "title": "Product Analyst",
            "company_name": "Dream11",
            "industry": "Gaming",
            "rating": 4.2,
            "location": "Mumbai, India",
            "work_mode": "Hybrid",
            "employment_type": "Full-time",
            "salary_min": 1000000,
            "salary_max": 1800000,
            "experience_required": "0-2 years",
            "deadline_offset": 13,
            "skills_required": [
                "SQL",
                "Python",
                "A/B Testing",
                "Statistics",
                "Tableau",
                "Excel",
            ],
            "description": "Drive product decisions with data for a fantasy sports platform. Design experiments, analyze retention, and build self-serve dashboards.",
            "benefits": ["Health insurance", "Gaming allowance"],
        },
        {
            "source_id": "internal:backend-intern",
            "source": "JobPilot",
            "title": "Backend Intern (Go)",
            "company_name": "Postman",
            "industry": "Developer Tools",
            "rating": 4.3,
            "location": "Bengaluru, India",
            "work_mode": "Onsite",
            "employment_type": "Internship",
            "salary_min": 50000,
            "salary_max": 75000,
            "experience_required": "Fresher",
            "deadline_offset": 21,
            "skills_required": [
                "Go",
                "Golang",
                "SQL",
                "Redis",
                "REST APIs",
                "Docker",
                "Git",
            ],
            "description": "Build backend services for the world's most popular API platform. Write Go services, design APIs, and learn from senior engineers.",
            "benefits": ["Stipend", "PPO opportunity", "Mentorship"],
        },
    ]

    created = 0
    with SessionLocal() as db:
        for item in seed_data:
            existing = db.scalar(select(Job).where(Job.source_id == item["source_id"]))
            if existing:
                continue
            company = db.scalar(
                select(Company).where(Company.name == item["company_name"])
            )
            if company is None:
                company = Company(
                    name=item["company_name"],
                    industry=item.get("industry"),
                    rating=item.get("rating"),
                )
                db.add(company)
                db.flush()
            job = Job(
                source_id=item["source_id"],
                source=item["source"],
                title=item["title"],
                company_id=company.id,
                company_name=company.name,
                location=item["location"],
                work_mode=item["work_mode"],
                employment_type=item["employment_type"],
                salary_min=item["salary_min"],
                salary_max=item["salary_max"],
                experience_required=item["experience_required"],
                description=item["description"],
                skills_required=item["skills_required"],
                benefits=item["benefits"],
                application_deadline=today + timedelta(days=item["deadline_offset"]),
                posted_at=datetime.now(timezone.utc)
                - timedelta(hours=item["deadline_offset"] * 3),
            )
            db.add(job)
            created += 1
        db.commit()
    return created


if __name__ == "__main__":
    init_db()
    n = seed_jobs()
    logger.info("Seeded %s jobs", n)
